/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { DownloadReportResponseData } from './downloadReportResponseData';


export interface APIResponseDownloadReportResponseData { 
    status?: StatusEnum;
    data?: DownloadReportResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponseDownloadReportResponseData {
}


