/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { FragmentResponseData } from './fragmentResponseData';


export interface APIResponseFragmentResponseData { 
    status?: StatusEnum;
    data?: FragmentResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponseFragmentResponseData {
}


