/**
 * DeepBDE API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';

export interface APIResponseNoneType {
  status?: StatusEnum;
  data?: null;
  error?: ErrorDetail | null;
}
export namespace APIResponseNoneType {}
