/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { PredictMultipleResponseData } from './predictMultipleResponseData';


export interface APIResponsePredictMultipleResponseData { 
    status?: StatusEnum;
    data?: PredictMultipleResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponsePredictMultipleResponseData {
}


