/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Información 2D de un átomo para visualización y metadatos. - x: Coordenada X - y: Coordenada Y - symbol: Símbolo químico del átomo (ej. \'C\', \'O\') - smiles: SMILES del átomo (opcional, para átomos complejos)
 */
export interface Atom2D { 
    x: number;
    y: number;
    symbol: string;
    smiles?: string | null;
}

