/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrada para /download_report/. - smiles: SMILES de la molécula - format:  \'txt\'
 */
export interface DownloadReportRequest { 
    smiles: string;
    format: string;
}

