/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeración de códigos de error estándar de la API.
 */
export const ErrorCode = {
    SmilesInvalid: 'SMILES_INVALID',
    BondIndexOutOfRange: 'BOND_INDEX_OUT_OF_RANGE',
    UnsupportedFormat: 'UNSUPPORTED_FORMAT',
    MissingExportOption: 'MISSING_EXPORT_OPTION'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

