/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Salida de /predict/info-smile-canonical/. - smiles: smile 
 */
export interface MoleculeSmileCanonicalRequest { 
    smiles: string;
}

