/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BondTypeEnum } from './bondTypeEnum';


/**
 * Detalle de un enlace químico y su BDE predicha. - idx: Índice del enlace en la molécula. - bde: Energía de disociación predicha para el enlace. - begin_atom_idx: Índice del átomo inicial del enlace. - end_atom_idx: Índice del átomo final del enlace. - bond_atoms: Representación legible del enlace (ejemplo: \'C-O\').
 */
export interface PredictedBond { 
    idx: number;
    bde: number | null;
    begin_atom_idx: number;
    end_atom_idx: number;
    bond_atoms: string;
    bond_type?: BondTypeEnum;
    is_fragmentable: boolean;
}
export namespace PredictedBond {
}


