/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrada para /predict/multiple/. - molecule_id: ID de la molécula - bond_indices: Lista de índices de enlaces - smiles: (opcional)
 */
export interface PredictMultipleRequest { 
    smiles: string;
    bond_indices: Array<number>;
    molecule_id: string;
}

