/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictedBond } from './predictedBond';


/**
 * Salida de /predict/single/. - smiles_canonical: SMILES canónico - bond: Detalle del enlace predicho
 */
export interface PredictSingleResponseData { 
    smiles_canonical: string;
    bond: PredictedBond;
}

