/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];

