/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { PredictCheckResponseData } from './predictCheckResponseData';


export interface APIResponsePredictCheckResponseData { 
    status?: StatusEnum;
    data?: PredictCheckResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponsePredictCheckResponseData {
}


