/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { MoleculeInfoResponseData } from './moleculeInfoResponseData';


export interface APIResponseMoleculeInfoResponseData { 
    status?: StatusEnum;
    data?: MoleculeInfoResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponseMoleculeInfoResponseData {
}


