/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { PredictSingleResponseData } from './predictSingleResponseData';


export interface APIResponsePredictSingleResponseData { 
    status?: StatusEnum;
    data?: PredictSingleResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponsePredictSingleResponseData {
}


