/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './errorDetail';
import { StatusEnum } from './statusEnum';
import { InferAllResponseData } from './inferAllResponseData';


export interface APIResponseInferAllResponseData { 
    status?: StatusEnum;
    data?: InferAllResponseData | null;
    error?: ErrorDetail | null;
}
export namespace APIResponseInferAllResponseData {
}


