/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BondTypeEnum } from './bondTypeEnum';


/**
 * Información 2D de un enlace para visualización y metadatos. - start: Índice del átomo inicial - end: Índice del átomo final - start_coords: Coordenadas del átomo inicial - end_coords: Coordenadas del átomo final - bond_atoms: Representación legible del enlace (ej. \'C-O\')
 */
export interface Bond2D { 
    start: number;
    end: number;
    start_coords: { [key: string]: number; };
    end_coords: { [key: string]: number; };
    bond_atoms: string;
    bond_type?: BondTypeEnum;
}
export namespace Bond2D {
}


