/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BondTypeEnum = {
    Single: 'single',
    Double: 'double',
    Triple: 'triple',
    Aromatic: 'aromatic'
} as const;
export type BondTypeEnum = typeof BondTypeEnum[keyof typeof BondTypeEnum];

