/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeEnum } from './typeEnum';


/**
 * Salida de /download_report/. - report_base64: Reporte en base64
 */
export interface DownloadReportResponseData { 
    type?: TypeEnum;
    report_base64: string;
}
export namespace DownloadReportResponseData {
}


