/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorCode } from './errorCode';


/**
 * Detalle de error estándar para respuestas de la API. - code: Código de error único (ErrorCode). - message: Descripción amigable del error.
 */
export interface ErrorDetail { 
    code: ErrorCode;
    message: string;
}
export namespace ErrorDetail {
}


