/**
 * DeepBDE API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fragmentos de la molécula.
 */
export interface Fragments {
  Smile1: string;
  Smile2: string;
}
