/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrada para /infer/all/. - smiles: SMILES de la molécula
 */
export interface InferAllRequest { 
    smiles: string;
}

