/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Atom2D } from './atom2D';
import { Bond2D } from './bond2D';


/**
 * Salida de /predict/. - smiles_canonical: SMILES canónico con hidrógenos explícitos - image_svg: Imagen SVG enriquecida - canvas: Metadatos del lienzo - atoms: Diccionario de información 2D de átomos - bonds: Diccionario de información 2D de enlaces - molecule_id: ID único (hash SHA256)
 */
export interface MoleculeInfoResponseData { 
    smiles_canonical: string;
    image_svg: string;
    canvas: { [key: string]: number; };
    atoms: { [key: string]: Atom2D; };
    bonds: { [key: string]: Bond2D; };
    molecule_id: string;
}

