/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictedBond } from './predictedBond';
import { Fragments } from './fragments';


/**
 * Salida de /ObtainBDEFragments/. - smiles_canonical: SMILES canónico de la molécula original - molecule_id: ID de la molécula - bonds_predicted: Lista de enlaces predichos - fragments: Fragmentos de la molécula
 */
export interface ObtainBDEFragmentsResponseData { 
    smiles_canonical: string;
    molecule_id: string;
    bonds_predicted: PredictedBond;
    fragments: Fragments;
}

