/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fragments } from './fragments';


/**
 * Entrada para /ObtainBDEFragments/. - smiles: SMILES de la molécula - fragments: Fragmentos de la molécula
 */
export interface ObtainBDEFragmentsRequest { 
    smiles: string;
    fragments: Fragments;
}

