/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictedBond } from './predictedBond';


/**
 * Salida de /predict/multiple/. - smiles: SMILES canónico - molecule_id: ID de la molécula - bonds: Lista de detalles de enlaces
 */
export interface PredictMultipleResponseData { 
    smiles: string;
    molecule_id: string;
    bonds: Array<PredictedBond>;
}

