/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrada para /predict/check/. - smiles: SMILES original - bond_idx: Índice del enlace - products: Lista de SMILES esperados
 */
export interface PredictCheckRequest { 
    smiles: string;
    molecule_id: string;
    bond_idx: number;
    products: Array<string>;
}

