/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrada para /predict/single/. - smiles: SMILES de la molécula - molecule_id: ID único de la molécula - bond_idx: Índice del enlace (>= 0)
 */
export interface PredictSingleRequest { 
    smiles: string;
    molecule_id: string;
    bond_idx: number;
}

