/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictedBond } from './predictedBond';


/**
 * Salida de /predict/check/. - smiles_canonical: SMILES canónico - bond: Detalle del enlace analizado - products: Lista de SMILES resultantes
 */
export interface PredictCheckResponseData { 
    smiles_canonical: string;
    bond: PredictedBond;
    are_same_products?: boolean;
    products: Array<string>;
}

