/**
 * DeepBDE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypeEnum = {
    Pdf: 'pdf',
    Txt: 'txt'
} as const;
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];

