[mypy]
exclude = ^(deepbde)/
# si usas Django (configparser no admite comentarios inline)
plugins = mypy_django_plugin.main
ignore_missing_imports = True
follow_imports = silent
strict = True
disallow_untyped_defs = True
[mypy.deepbde.*]
ignore_errors = True
ignore_missing_imports = True
[mypy.rdkit.*]
ignore_errors = True
ignore_missing_imports = True